import { test, expect } from '@playwright/test';

test.use({
  storageState: 'tests/playwright-auth-sessions/session-john@foo.com.json',
});

test('test', async ({ page }) => {
  await page.goto('https://rainbow-reclamation.vercel.app/');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('john@foo.com');
  await page.getByRole('textbox', { name: 'Password' }).dblclick();
  await page.getByRole('textbox', { name: 'Password' }).fill('changeme');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Browse Found Items' }).click();
  await page.getByRole('button', { name: 'Claim Item' }).nth(1).click();
  await page.getByRole('link', { name: 'My Dashboard' }).click();
  await page.getByRole('link', { name: 'Browse Items' }).click();
  await page.getByRole('link', { name: 'My Dashboard' }).click();
  await page.getByRole('link', { name: 'My Dashboard' }).click();
  await page.getByRole('link', { name: 'View All Listings' }).click();
  await page.getByRole('button', { name: 'Claim Item' }).nth(1).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Report Lost Item' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Create Your Account' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'My Dashboard' }).click();
  await page.getByRole('link', { name: 'Homepage' }).click();
  await page.getByRole('button', { name: 'john@foo.com' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Sign in' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('admin@foo.com');
  await page.getByRole('textbox', { name: 'Password' }).dblclick();
  await page.getByRole('textbox', { name: 'Password' }).fill('changeme');
  await page.locator('form').getByRole('button', { name: 'Login' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Browse Found Items' }).click();
  await page.getByRole('button', { name: 'Claim Item' }).nth(1).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Report Lost Item' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'View All Listings' }).click();
  await page.getByRole('button', { name: 'Claim Item' }).nth(1).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Create Your Account' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Browse Items' }).click();
  await page.getByRole('button', { name: 'Claim Item' }).nth(2).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('link', { name: 'Report Lost Item' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: 'Manage Users' }).click();
  await page.getByRole('button', { name: 'View Reports' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('button', { name: 'New Posting' }).click();
  await page.getByRole('link', { name: 'Admin' }).click();
  await page.getByRole('link', { name: 'My Dashboard' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
  await page.getByRole('button', { name: 'admin@foo.com' }).click();
  await page.getByRole('link', { name: 'Sign Out' }).click();
  await page.getByRole('button', { name: 'Sign Out' }).click();
  await page.getByRole('link', { name: 'Rainbow Reclamation' }).click();
});
