name: Issue
description: Create an issue in Rainbow Reclamation.
projects: "rainbow-reclamation/M1"
body:
  - type: textarea
    attributes:
      label: What is the issue?
      description: Replace 'XX' with the issue number and fill out what needs to be accomplished for this task.
      placeholder: What is the issue?
      value: "Do all work for this task in a branch called issue-XX. "
    validations:
      required: true
